name: xeus-python
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  # Host dependencies
  - xeus>=1.0.1,<2
  - nlohmann_json
  - cppzmq
  - xtl=0.7.0
  - jedi>=0.15.1,<0.18
  - pybind11=2.6.0
  - pybind11_json>=0.2.6,<0.3
  - ipython>=7.14.0,<8
  - debugpy
  # Test dependencies
  - pytest
  - nbval
  - ipympl
